# Generated by Django 3.2.5 on 2021-08-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gmail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
