# Generated by Django 3.2.5 on 2021-08-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profile_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.CharField(blank=True, default='cv1', max_length=250, null=True),
        ),
    ]
