# Generated by Django 3.2.5 on 2021-08-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cv',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
