# Generated by Django 3.2.5 on 2021-08-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210827_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gmail',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
