export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL'
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET'

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET'

export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST'
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS'
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL'
export const PROFILE_DETAILS_RESET = 'PROFILE_DETAILS_RESET'

export const USER_INFO_UPDATE_REQUEST = 'USER_INFO_UPDATE_REQUEST'
export const USER_INFO_UPDATE_SUCCESS = 'USER_INFO_UPDATE_SUCCESS'
export const USER_INFO_UPDATE_FAIL = 'USER_INFO_UPDATE_FAIL'
export const USER_INFO_UPDATE_RESET = 'USER_INFO_UPDATE_RESET'

export const SKILL_ADD_REQUEST = 'SKILL_ADD_REQUEST'
export const SKILL_ADD_SUCCESS = 'SKILL_ADD_SUCCESS'
export const SKILL_ADD_FAIL = 'SKILL_ADD_FAIL'
export const SKILL_ADD_RESET = 'SKILL_ADD_RESET'

export const SKILL_DELETE_REQUEST = 'SKILL_DELETE_REQUEST'
export const SKILL_DELETE_SUCCESS = 'SKILL_DELETE_SUCCESS'
export const SKILL_DELETE_FAIL = 'SKILL_DELETE_FAIL'

export const Education_ADD_REQUEST = 'Education_ADD_REQUEST'
export const Education_ADD_SUCCESS = 'Education_ADD_SUCCESS'
export const Education_ADD_FAIL = 'Education_ADD_FAIL'
export const Education_ADD_RESET = 'Education_ADD_RESET'

export const Education_DELETE_REQUEST = 'Education_DELETE_REQUEST'
export const Education_DELETE_SUCCESS = 'Education_DELETE_SUCCESS'
export const Education_DELETE_FAIL = 'Education_DELETE_FAIL'

export const Experience_ADD_REQUEST = 'Experience_ADD_REQUEST'
export const Experience_ADD_SUCCESS = 'Experience_ADD_SUCCESS'
export const Experience_ADD_FAIL = 'Experience_ADD_FAIL'
export const Experience_ADD_RESET = 'Experience_ADD_RESET'

export const Experience_DELETE_REQUEST = 'Experience_DELETE_REQUEST'
export const Experience_DELETE_SUCCESS = 'Experience_DELETE_SUCCESS'
export const Experience_DELETE_FAIL = 'Experience_DELETE_FAIL'

export const Language_ADD_REQUEST = 'Language_ADD_REQUEST'
export const Language_ADD_SUCCESS = 'Language_ADD_SUCCESS'
export const Language_ADD_FAIL = 'Language_ADD_FAIL'
export const Language_ADD_RESET = 'Language_ADD_RESET'

export const Language_DELETE_REQUEST = 'Language_DELETE_REQUEST'
export const Language_DELETE_SUCCESS = 'Language_DELETE_SUCCESS'
export const Language_DELETE_FAIL = 'Language_DELETE_FAIL'

export const PROFILE_INFO_DETAILS_BY_ID_REQUEST = 'PROFILE_INFO_DETAILS_BY_ID_REQUEST'
export const PROFILE_INFO_DETAILS_BY_ID_SUCCESS = 'PROFILE_INFO_DETAILS_BY_ID_SUCCESS'
export const PROFILE_INFO_DETAILS_BY_ID_FAIL = 'PROFILE_INFO_DETAILS_BY_ID_FAIL'
export const PROFILE_INFO_DETAILS_BY_ID_RESET = 'PROFILE_INFO_DETAILS_BY_ID_RESET'

export const UPDATE_CV_REQUEST = 'UPDATE_CV_REQUEST'
export const UPDATE_CV_SUCCESS = 'UPDATE_CV_SUCCESS'
export const UPDATE_CV_FAIL = 'UPDATE_CV_FAIL'
export const UPDATE_CV_RESET = 'UPDATE_CV_RESET'